apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    myapp: dcanadillas-demo
    tier: front
spec:
  selector:
    myapp: dcanadillas-demo
    tier: front
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: dcanadillas-demo
    tier: front

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: dcanadillas-demo
    #myapp: dcanadillas-demo
    tier: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcanadillas-demo
      tier: front
  template:
    metadata:
      labels:
        app: dcanadillas-demo
        tier: front
        myapp: dcanadillas-demo
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "frontend"
        # consul.hashicorp.com/kubernetes-service: "frontend"
        # consul.hashicorp.com/service-tags: v1.4
        # consul.hashicorp.com/connect-service-upstreams: "backend:9090"
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: hcdcanadillas/pydemo-front:v1.4
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: BACKEND_URL
              # value: "http://backend:8080"
              value: "http://backend.virtual.dc2-default.consul:8080"